version: "3"

services:
  server:
    container_name: AVALIACAO_VERX_API
    build: "."
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - 3000:3000

  db:
    image: "mongo"
    container_name: AVALIACAO_VERX_MONGO
    ports:
      - "27017:27017"
    volumes:
      - ./data/
